services:
  opensearch:
    image: opensearchproject/opensearch:3
    container_name: opensearch
    environment:
      discovery.type: "single-node"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "OpenSearchTest123!"
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -k -u admin:OpenSearchTest123! https://localhost:9200 >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 20

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3
    container_name: opensearch-dashboards
    depends_on:
      opensearch:
        condition: service_healthy
    volumes:
      - ./opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml:ro
    ports:
      - "5601:5601"

volumes:
  opensearch_data: