services:
  opensearch:
    image: opensearchproject/opensearch:3
    container_name: opensearch
    environment:
      discovery.type: "single-node"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "OpenSearchTest123!"
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -k -u admin:OpenSearchTest123! https://localhost:9200 >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 20

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3
    container_name: opensearch-dashboards
    depends_on:
      opensearch:
        condition: service_healthy
    volumes:
      - ./opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml:ro
    ports:
      - "5601:5601"

  rag-api:
    build:
      context: ./rag_api
    container_name: rag-api
    depends_on:
      opensearch:
        condition: service_healthy
    environment:
      INDEX_NAME: ovf-docs
      OPENSEARCH_MODEL_ID: "${OPENSEARCH_MODEL_ID}"
      HYBRID_SEARCH_PIPELINE: ovf-hybrid-pipeline

      OPENSEARCH_HOST: opensearch
      OPENSEARCH_PORT: 9200
      OPENSEARCH_USER: admin
      OPENSEARCH_PASSWORD: OpenSearchTest123!
      OPENSEARCH_USE_SSL: "true"
      OPENSEARCH_VERIFY_CERTS: "false"

      OLLAMA_HOST: http://ollama:11434
      OLLAMA_CHAT_MODEL: gemma3:12b

      DEFAULT_RETRIEVER: semantic
      DEFAULT_TOP_K: 8
      PORT: 8000
    ports:
      - "8000:8000"

volumes:
  opensearch_data: